# Generated by Django 4.2.18 on 2025-04-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_passwordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='student',
            new_name='user',
        ),
    ]
