# Generated by Django 4.2.18 on 2025-04-19 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_leaverequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='submitted_on',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 19, 15, 44, 7, 396168, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
