# Generated by Django 5.2.8 on 2026-01-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_dailyattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='category',
            field=models.CharField(choices=[('illness', 'Illness'), ('appointment', 'Appointment'), ('family', 'Family Matter'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.DeleteModel(
            name='DailyAttendance',
        ),
    ]
