# Generated by Django 5.2.8 on 2026-02-13 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_leaverequest_category_delete_dailyattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='AttendanceDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100)),
                ('student_code', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('remarks', models.TextField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('records_count', models.IntegerField(default=0)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.student')),
            ],
            options={
                'verbose_name': 'Attendance Deletion Log',
                'verbose_name_plural': 'Attendance Deletion Logs',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
